# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_auto_20171218_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nome',
            name='Endereco',
            field=models.CharField(max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='nome',
            name='NomeCompleto',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
    ]
