# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('document', models.FileField(upload_to='documents/', verbose_name='Documento')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Carregado em')),
            ],
        ),
    ]
